helm uninstall   redis 
helm uninstall   adservice 
helm uninstall   cartservice 
helm uninstall  checkoutservice 
helm uninstall  currencyservice 
helm uninstall   email-service-values 
helm uninstall   frontend 
helm uninstall  payment-svc 
helm uninstall  productcatalog 
helm uninstall  recommendation 
helm uninstall  shoppingservice 
