apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName}}
spec:
  selector:
    app: {{ .Values.appName}}
  type: ClusterIP
  ports:
  - name: {{ .Values.appName}}
    protocol: TCP
    port: {{.Values.servicePort}}
    targetPort: {{.Values.containerPort}}